baseURL = 'https://disknotifier.com/'
languageCode = 'en-us'
title = 'Disk Notifier - Disk space monitoring made easy'
theme = "beans"
enableGitInfo = true

[build]
  writeStats = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
