baseURL = 'https://stoic-brown-842f62.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "beans"
[build]
  writeStats = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
